# Generated by Django 5.1.3 on 2026-04-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('wikipedia_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'bookshelves',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('language', models.CharField(db_index=True, max_length=20)),
                ('downloads', models.IntegerField(default=0)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('rights', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('transcribers', models.CharField(blank=True, max_length=1000)),
                ('reading_ease', models.CharField(blank=True, max_length=300)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='api.author')),
                ('bookshelves', models.ManyToManyField(blank=True, related_name='books', to='api.bookshelf')),
                ('subjects', models.ManyToManyField(blank=True, related_name='books', to='api.subject')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('mime_type', models.CharField(db_index=True, max_length=100)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='api.book')),
            ],
            options={
                'db_table': 'book_formats',
            },
        ),
    ]
