# Generated by Django 5.1.3 on 2026-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_bookshelf_subject_book_bookformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='transcribers',
            field=models.TextField(blank=True),
        ),
    ]
