# Generated by Django 5.1.3 on 2026-04-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_bookshelves', to='api.bookshelf'),
        ),
    ]
