# Generated by Django 5.1.3 on 2026-04-25 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_reading_ease_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='scroll_percent',
        ),
        migrations.AddField(
            model_name='highlight',
            name='section_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature Request'), ('general', 'General'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
    ]
